# Generated by Django 3.0.10 on 2021-02-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_externallink', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link title')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_footer', serialize=False, to='cms.CMSPlugin')),
                ('location_link', models.URLField(blank=True, default='https://goo.gl/maps/gfMW9BYgLwjTVcSk7', null=True, verbose_name='Location link')),
                ('location_country', models.CharField(blank=True, default='Україна', max_length=100, null=True, verbose_name='Location country')),
                ('location_city', models.CharField(blank=True, default='м. Херсон', max_length=100, null=True, verbose_name='Location city')),
                ('location_street', models.CharField(blank=True, default='вул. Стрітенська, 23', max_length=100, null=True, verbose_name='Location street')),
                ('location_zip', models.CharField(blank=True, default='73006', max_length=100, null=True, verbose_name='Location zip')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook link')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram link')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Youtube link')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram link')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='Linkedin link')),
                ('phone1', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Phone')),
                ('phone2', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Phone')),
                ('email1', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Email')),
                ('email2', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
