# Generated by Django 3.0.10 on 2021-02-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_universitysite_universitysitetranslation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='universitysite',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='universitysite',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='seo'),
        ),
        migrations.AddField(
            model_name='universitysite',
            name='og_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitysite',
            name='twitter_card',
            field=models.IntegerField(choices=[(1, 'summary'), (2, 'summary_large_image'), (3, 'app'), (4, 'player')], null=True),
        ),
        migrations.AddField(
            model_name='universitysite',
            name='twitter_image',
            field=models.ImageField(blank=True, upload_to='seo'),
        ),
        migrations.AddField(
            model_name='universitysite',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='universitysitetranslation',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='universitysitetranslation',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='universitysitetranslation',
            name='og_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='universitysitetranslation',
            name='og_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='universitysitetranslation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
