# Generated by Django 3.0.10 on 2021-02-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210209_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitysitetranslation',
            name='twitter_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
