# Generated by Django 3.0.10 on 2021-02-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_universitysitetranslation_twitter_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitysite',
            name='primary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
