# Generated by Django 3.0.10 on 2021-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_universitysite_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitysite',
            name='twitter_card',
            field=models.IntegerField(blank=True, choices=[(1, 'summary'), (2, 'summary_large_image'), (3, 'app'), (4, 'player')], null=True),
        ),
    ]
