# Generated by Django 3.0.10 on 2021-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_banner_cards_info1_info2_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='phone1',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='phone2',
        ),
        migrations.AddField(
            model_name='footer',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True, verbose_name='Tiktok link'),
        ),
    ]
