# Generated by Django 3.0.10 on 2021-02-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210218_1716'),
        ('content', '0009_auto_20210218_1713'),
    ]

    operations = [
    ]
