# Generated by Django 3.0.10 on 2021-02-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210218_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='header',
        ),
        migrations.AddField(
            model_name='banner',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='cms', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='left_card_image',
            field=models.FileField(upload_to='cms', verbose_name='Left card image'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='middle_card_image',
            field=models.FileField(upload_to='cms', verbose_name='Middle card image'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='right_card_image',
            field=models.FileField(upload_to='cms', verbose_name='Right card image'),
        ),
    ]
