# Generated by Django 3.0.10 on 2021-02-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210218_1739'),
        ('content', '0010_merge_20210218_1728'),
    ]

    operations = [
    ]
