# Generated by Django 3.0.10 on 2021-02-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_merge_20210218_1741'),
        ('content', '0011_contactrequest'),
    ]

    operations = [
    ]
