# Generated by Django 3.0.10 on 2021-02-27 15:54

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('content', '0011_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_section', serialize=False, to='cms.CMSPlugin')),
                ('content', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Content')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='cards',
            name='left_card_url',
            field=models.URLField(blank=True, null=True, verbose_name='Left card url'),
        ),
        migrations.AddField(
            model_name='cards',
            name='middle_card_url',
            field=models.URLField(blank=True, null=True, verbose_name='Middle card url'),
        ),
        migrations.AddField(
            model_name='cards',
            name='right_card_url',
            field=models.URLField(blank=True, null=True, verbose_name='Right card url'),
        ),
    ]
