# Generated by Django 3.0.10 on 2021-02-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_merge_20210227_0016'),
        ('content', '0012_auto_20210227_1754'),
    ]

    operations = [
    ]
