# Generated by Django 3.0.10 on 2021-02-27 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0030_auto_20210223_2034'),
        ('cms', '0022_auto_20180620_1551'),
        ('content', '0013_hidingsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersSliderStaff',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_teacherssliderstaff', serialize=False, to='cms.CMSPlugin')),
                ('rank', models.CharField(blank=True, max_length=300, null=True, verbose_name='Rank')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Staff', verbose_name='Staff')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TeacherSlider',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_teacherslider', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=150, verbose_name='Section title')),
                ('staff', models.ManyToManyField(to='content.TeachersSliderStaff', verbose_name='Staff')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
