# Generated by Django 3.0.10 on 2021-02-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_hidingsection'),
        ('content', '0013_merge_20210227_1755'),
    ]

    operations = [
    ]
