# Generated by Django 3.0.10 on 2021-02-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_merge_20210227_1956'),
        ('content', '0014_teacherslider_teacherssliderstaff'),
    ]

    operations = [
    ]
