# Generated by Django 3.0.10 on 2021-02-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('university', '0030_auto_20210223_2034'),
        ('content', '0014_teacherslider_teacherssliderstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherslider',
            name='staff',
            field=models.ManyToManyField(help_text='You can choose staff from cathedra staff', to='university.StaffCathedra', verbose_name='Staff'),
        ),
        migrations.DeleteModel(
            name='TeachersSliderStaff',
        ),
    ]
