# Generated by Django 3.0.10 on 2021-02-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_merge_20210227_2243'),
        ('content', '0015_auto_20210227_2255'),
    ]

    operations = [
    ]
