# Generated by Django 3.0.10 on 2021-02-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20210228_1324'),
        ('content', '0016_merge_20210227_2255'),
    ]

    operations = [
    ]
