# Generated by Django 3.0.10 on 2021-03-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_merge_20210228_1325'),
        ('content', '0017_internallink'),
    ]

    operations = [
    ]
