# Generated by Django 3.1.5 on 2021-02-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210129_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='large_image',
        ),
        migrations.AddField(
            model_name='image',
            name='medium_image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='image',
            name='small_image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
