# Generated by Django 3.0.10 on 2021-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210203_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large_image',
            field=models.ImageField(default='', max_length=400, upload_to='gallery', verbose_name='Image'),
        ),
    ]
