# Generated by Django 3.1.5 on 2021-02-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210202_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large_image',
            field=models.ImageField(default='', max_length=400, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium_image',
            field=models.ImageField(blank=True, default='', max_length=400, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='small_image',
            field=models.ImageField(blank=True, default='', max_length=400, upload_to='images'),
        ),
    ]
