# Generated by Django 3.0.10 on 2021-02-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210205_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large_image',
            field=models.ImageField(default='', upload_to='gallery', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium_image',
            field=models.ImageField(blank=True, default='', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='image',
            name='small_image',
            field=models.ImageField(blank=True, default='', upload_to='gallery'),
        ),
    ]
