# Generated by Django 3.0.10 on 2021-02-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210206_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large_image',
            field=models.ImageField(default='', max_length=300, upload_to='gallery', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium_image',
            field=models.ImageField(blank=True, default='', max_length=300, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='image',
            name='small_image',
            field=models.ImageField(blank=True, default='', max_length=300, upload_to='gallery'),
        ),
    ]
