# Generated by Django 3.1.5 on 2021-01-28 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multi_email_field.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emblem', models.ImageField(default='', upload_to='cathedras/emblems', verbose_name='Emblem')),
                ('number', models.CharField(default='', max_length=20, verbose_name='Number')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Cathedra',
                'verbose_name_plural': 'Cathedras',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emblem', models.ImageField(default='', upload_to='faculties/emblems', verbose_name='Emblem')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery', verbose_name='Gallery')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=10, verbose_name='Number')),
                ('cathedra', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.cathedra', verbose_name='Cathedra')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Photo')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('emails', multi_email_field.fields.MultiEmailField(default=[])),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.library', verbose_name='Library')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaffCathedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathedras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.cathedra', verbose_name='Cathedra')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Cathedra staff',
                'verbose_name_plural': 'Cathedra staffs',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaffFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.faculty', verbose_name='Faculty')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Faculty staff',
                'verbose_name_plural': 'Faculty staffs',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_scholar', models.URLField(blank=True, null=True, verbose_name='Google Scholar')),
                ('web_of_science', models.URLField(blank=True, null=True, verbose_name='Web Of Science')),
                ('researchgate', models.URLField(blank=True, null=True, verbose_name='Researchgate')),
                ('scopus', models.URLField(blank=True, null=True, verbose_name='Scopus')),
                ('orcid', models.URLField(blank=True, null=True, verbose_name='ORCID')),
                ('staff', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Links',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='staffs',
            field=models.ManyToManyField(to='university.StaffFaculty', verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.faculty', verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery', verbose_name='Gallery'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='staffs',
            field=models.ManyToManyField(to='university.StaffCathedra', verbose_name='Staff'),
        ),
        migrations.CreateModel(
            name='StaffTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(max_length=1500, verbose_name='Description')),
                ('second_name', models.CharField(max_length=40, verbose_name='Second name')),
                ('first_name', models.CharField(max_length=40, verbose_name='First name')),
                ('third_name', models.CharField(max_length=40, verbose_name='Third name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='university.staff')),
            ],
            options={
                'verbose_name': 'Staff Translation',
                'db_table': 'university_staff_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaffFacultyTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='university.stafffaculty')),
            ],
            options={
                'verbose_name': 'Faculty staff Translation',
                'db_table': 'university_stafffaculty_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaffCathedraTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('rank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rank')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='university.staffcathedra')),
            ],
            options={
                'verbose_name': 'Cathedra staff Translation',
                'db_table': 'university_staffcathedra_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SpecialityTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(default='', max_length=1500, verbose_name='Description')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='university.speciality')),
            ],
            options={
                'verbose_name': 'Speciality Translation',
                'db_table': 'university_speciality_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FacultyTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(default='', max_length=1500, verbose_name='Description')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='university.faculty')),
            ],
            options={
                'verbose_name': 'Faculty Translation',
                'db_table': 'university_faculty_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CathedraTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(default='', max_length=1500, verbose_name='Description')),
                ('goal', models.TextField(default='', max_length=1500, verbose_name='Goal')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='university.cathedra')),
            ],
            options={
                'verbose_name': 'Cathedra Translation',
                'db_table': 'university_cathedra_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
