# Generated by Django 3.1.5 on 2021-01-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='staff',
            name='rank',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='staff',
            name='second_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='staff',
            name='third_name',
            field=models.CharField(max_length=40),
        ),
    ]
