# Generated by Django 3.0.10 on 2021-02-03 17:26

from django.db import migrations, models
import django.db.models.deletion
import multi_email_field.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificSociety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('emails', multi_email_field.fields.MultiEmailField(default=[])),
                ('staff', models.ManyToManyField(to='university.Staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Scientific Society',
                'verbose_name_plural': 'Scientific Societies',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='facultytranslation',
            name='council_of_employers',
            field=models.TextField(default='', verbose_name='Council of employers'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='scientific_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_society', to='university.ScientificSociety', verbose_name='Scientific Societies'),
        ),
        migrations.CreateModel(
            name='ScientificSocietyTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(default='', max_length=1500, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='university.ScientificSociety')),
            ],
            options={
                'verbose_name': 'Scientific Society Translation',
                'db_table': 'university_scientificsociety_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
