# Generated by Django 3.0.10 on 2021-02-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20210203_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificsocietytranslation',
            name='sub_title',
            field=models.CharField(default='', max_length=400, verbose_name='Sub title'),
        ),
    ]
