# Generated by Django 3.1.5 on 2021-01-22 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('university', '0002_auto_20210122_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cathedra',
            options={'verbose_name': 'Cathedra', 'verbose_name_plural': 'Cathedras'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Cathedra', 'verbose_name_plural': 'Cathedras'},
        ),
        migrations.AddField(
            model_name='cathedra',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='description',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='emblem',
            field=models.ImageField(default='', upload_to='emblems'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.faculty'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='goal',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='faculty',
            name='emblem',
            field=models.ImageField(default='', upload_to='emblems'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='speciality',
            name='cathedra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.cathedra'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='speciality',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='speciality',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
