# Generated by Django 3.1.5 on 2021-01-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20210122_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcathedra',
            name='cathedra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.cathedra'),
        ),
        migrations.AddField(
            model_name='staffcathedra',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffcathedra',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.staff'),
        ),
        migrations.AddField(
            model_name='stafffaculty',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.faculty'),
        ),
        migrations.AddField(
            model_name='stafffaculty',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stafffaculty',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
