# Generated by Django 3.0.10 on 2021-02-03 17:58

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_scientificsocietytranslation_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificsocietytranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', max_length=1500, verbose_name='Description'),
        ),
    ]
