# Generated by Django 3.0.10 on 2021-02-03 18:07

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20210203_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedratranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cathedratranslation',
            name='goal',
            field=models.TextField(default='', verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='facultytranslation',
            name='council_of_employers',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Council of employers'),
        ),
        migrations.AlterField(
            model_name='facultytranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='scientificsociety',
            name='staff',
            field=models.ManyToManyField(to='university.Staff', verbose_name='Staffs'),
        ),
        migrations.AlterField(
            model_name='scientificsocietytranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='specialitytranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stafftranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stafftranslation',
            name='methodical_works',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Methodical works'),
        ),
    ]
