# Generated by Django 3.1.5 on 2021-01-25 07:16

from django.db import migrations
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20210122_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Speciality', 'verbose_name_plural': 'Specialities'},
        ),
        migrations.AddField(
            model_name='staff',
            name='emails',
            field=multi_email_field.fields.MultiEmailField(default=[]),
        ),
    ]
