# Generated by Django 3.0.10 on 2021-02-04 12:01

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import multi_email_field.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20210203_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBaseNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Material-technical base',
                'verbose_name_plural': 'Material-technical bases',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='cathedra',
            name='number',
        ),
        migrations.AddField(
            model_name='cathedra',
            name='catalog_of_disciplines',
            field=models.URLField(blank=True, null=True, verbose_name='Catalog of disciplines link'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='educational_programs',
            field=models.URLField(blank=True, null=True, verbose_name='Educational programs link'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='emails',
            field=multi_email_field.fields.MultiEmailField(default=[]),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='year',
            field=models.IntegerField(choices=[(2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950)], null=True, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='cathedratranslation',
            name='history',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='History of cathedra'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='material_technical_base',
            field=models.ManyToManyField(to='university.MaterialBaseNode', verbose_name='Material-technical base'),
        ),
        migrations.CreateModel(
            name='MaterialBaseNodeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('local_title', models.CharField(help_text='Additional field with local name for best admin usage experience.\nWill be filled from title field, if field empty.', max_length=100, verbose_name='Local title')),
                ('content', djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='university.MaterialBaseNode')),
            ],
            options={
                'verbose_name': 'Material-technical base Translation',
                'db_table': 'university_materialbasenode_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
