# Generated by Django 3.1.5 on 2021-01-27 10:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0009_auto_20210127_1214'),
        ('gallery', '0004_auto_20210127_1214'),
        ('university', '0005_auto_20210125_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='rank',
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='description',
            field=models.TextField(default='', max_length=1500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='emblem',
            field=models.ImageField(default='', upload_to='emblems', verbose_name='Emblem'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery', verbose_name='Gallery'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='goal',
            field=models.TextField(default='', max_length=1500, verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='number',
            field=models.CharField(default='', max_length=20, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.TextField(default='', max_length=1500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='emblem',
            field=models.ImageField(default='', upload_to='emblems', verbose_name='Emblem'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery', verbose_name='Gallery'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='links',
            name='google_scholar',
            field=models.URLField(blank=True, null=True, verbose_name='Google Scholar'),
        ),
        migrations.AlterField(
            model_name='links',
            name='orcid',
            field=models.URLField(blank=True, null=True, verbose_name='ORCID'),
        ),
        migrations.AlterField(
            model_name='links',
            name='researchgate',
            field=models.URLField(blank=True, null=True, verbose_name='Researchgate'),
        ),
        migrations.AlterField(
            model_name='links',
            name='scopus',
            field=models.URLField(blank=True, null=True, verbose_name='Scopus'),
        ),
        migrations.AlterField(
            model_name='links',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.staff', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='links',
            name='web_of_science',
            field=models.URLField(blank=True, null=True, verbose_name='Web Of Science'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='cathedra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.cathedra', verbose_name='Cathedra'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='description',
            field=models.TextField(default='', max_length=1500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='number',
            field=models.CharField(default='', max_length=10, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.library', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(upload_to='photos', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='second_name',
            field=models.CharField(max_length=40, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='third_name',
            field=models.CharField(max_length=40, verbose_name='Third name'),
        ),
        migrations.AlterField(
            model_name='staffcathedra',
            name='cathedra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.cathedra', verbose_name='Cathedra'),
        ),
        migrations.AlterField(
            model_name='staffcathedra',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='staffcathedra',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.staff', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='stafffaculty',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='stafffaculty',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='stafffaculty',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.staff', verbose_name='Staff'),
        ),
    ]
