# Generated by Django 3.1.5 on 2021-01-27 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20210127_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
