# Generated by Django 3.0.10 on 2021-02-04 12:06

from django.db import migrations
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20210204_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='emails',
            field=multi_email_field.fields.MultiEmailField(blank=True, default=[], null=True),
        ),
    ]
