# Generated by Django 3.0.10 on 2021-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20210204_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbasenodetranslation',
            name='local_title',
            field=models.CharField(blank=True, help_text='Additional field with local name for best admin usage experience.\nWill be filled from title field, if field empty.', max_length=100, null=True, verbose_name='Local title'),
        ),
        migrations.AlterField(
            model_name='materialbasenodetranslation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
