# Generated by Django 3.1.5 on 2021-01-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20210127_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffcathedra',
            options={'verbose_name': 'Cathedra staff', 'verbose_name_plural': 'Cathedra staffs'},
        ),
        migrations.AlterModelOptions(
            name='stafffaculty',
            options={'verbose_name': 'Faculty staff', 'verbose_name_plural': 'Faculty staffs'},
        ),
        migrations.RenameField(
            model_name='staffcathedra',
            old_name='cathedra',
            new_name='cathedras',
        ),
        migrations.RenameField(
            model_name='stafffaculty',
            old_name='faculty',
            new_name='faculties',
        ),
        migrations.AddField(
            model_name='cathedra',
            name='staffs',
            field=models.ManyToManyField(to='university.StaffCathedra', verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='staffs',
            field=models.ManyToManyField(to='university.StaffFaculty', verbose_name='Staff'),
        ),
    ]
