# Generated by Django 3.1.5 on 2021-01-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20210127_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='emblem',
            field=models.ImageField(default='', upload_to='cathedras/emblems', verbose_name='Emblem'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='emblem',
            field=models.ImageField(default='', upload_to='faculties/emblems', verbose_name='Emblem'),
        ),
    ]
