# Generated by Django 3.0.10 on 2021-02-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210203_2007'),
        ('university', '0009_auto_20210204_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cathedras', to='gallery.Gallery', verbose_name='Career guidance'),
        ),
    ]
