# Generated by Django 3.0.10 on 2021-02-04 17:43

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20210204_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftranslation',
            name='ndr_theme',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Topics of research work'),
        ),
        migrations.AlterField(
            model_name='stafftranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stafftranslation',
            name='methodical_works',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Methodical works'),
        ),
    ]
