# Generated by Django 3.0.10 on 2021-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20210204_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftranslation',
            name='ndr_theme',
            field=models.TextField(blank=True, verbose_name='Topics of research work'),
        ),
    ]
