# Generated by Django 3.0.10 on 2021-02-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_auto_20210204_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialitytranslation',
            name='educational_level',
            field=models.CharField(choices=[('Junior bachelor', 'Junior bachelor'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctor of Philosophy', 'Doctor of Philosophy'), ('PHD', 'PHD')], max_length=200, null=True, verbose_name='Educational Level'),
        ),
    ]
