# Generated by Django 3.0.10 on 2021-02-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_specialitytranslation_educational_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='material_technical_base',
            field=models.ManyToManyField(blank=True, to='university.MaterialBaseNode', verbose_name='Material-technical base'),
        ),
        migrations.AlterField(
            model_name='scientificsociety',
            name='staff',
            field=models.ManyToManyField(related_name='staff', to='university.Staff', verbose_name='Staffs'),
        ),
        migrations.AlterField(
            model_name='specialitytranslation',
            name='educational_level',
            field=models.CharField(choices=[('Junior bachelor', 'Junior bachelor'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PHD', 'PHD'), ('Doctor of Philosophy', 'Doctor of Philosophy')], max_length=200, null=True, verbose_name='Educational Level'),
        ),
    ]
