# Generated by Django 3.0.10 on 2021-02-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_auto_20210205_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='scientificsociety',
            name='staff',
        ),
        migrations.AddField(
            model_name='staff',
            name='disciplines',
            field=models.ManyToManyField(to='university.Discipline'),
        ),
    ]
