# Generated by Django 3.0.10 on 2021-02-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_auto_20210208_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='google_scholar',
            field=models.URLField(blank=True, null=True, verbose_name='Google Scholar'),
        ),
        migrations.AddField(
            model_name='staff',
            name='orcid',
            field=models.URLField(blank=True, null=True, verbose_name='ORCID'),
        ),
        migrations.AddField(
            model_name='staff',
            name='researchgate',
            field=models.URLField(blank=True, null=True, verbose_name='Researchgate'),
        ),
        migrations.AddField(
            model_name='staff',
            name='scopus',
            field=models.URLField(blank=True, null=True, verbose_name='Scopus'),
        ),
        migrations.AddField(
            model_name='staff',
            name='web_of_science',
            field=models.URLField(blank=True, null=True, verbose_name='Web Of Science'),
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
