# Generated by Django 3.0.10 on 2021-02-08 09:21

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_auto_20210208_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedratranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='facultytranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='specialitytranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Description'),
        ),
    ]
