# Generated by Django 3.0.10 on 2021-02-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_auto_20210208_1304'),
        ('university', '0018_auto_20210208_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='library',
        ),
        migrations.AddField(
            model_name='staff',
            name='books',
            field=models.ManyToManyField(blank=True, to='library.Book'),
        ),
    ]
