# Generated by Django 3.0.10 on 2021-02-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0019_auto_20210208_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialitytranslation',
            name='form_of_studying',
            field=models.CharField(choices=[('Day', 'Day'), ('Extramural', 'Extramural'), ('Day, Extramural', 'Day, Extramural')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffcathedratranslation',
            name='rank',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='stafffacultytranslation',
            name='position',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='stafftranslation',
            name='rank',
            field=models.CharField(blank=True, max_length=300, verbose_name='Rank'),
        ),
    ]
