# Generated by Django 3.0.10 on 2021-02-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0019_auto_20210208_1236'),
        ('university', '0019_auto_20210208_1304'),
    ]

    operations = [
    ]
