# Generated by Django 3.0.10 on 2021-02-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0020_merge_20210208_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcathedratranslation',
            name='rank',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='stafffacultytranslation',
            name='position',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='stafftranslation',
            name='rank',
            field=models.CharField(blank=True, max_length=300, verbose_name='Rank'),
        ),
    ]
