# Generated by Django 3.0.10 on 2021-02-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0020_merge_20210208_1859'),
        ('university', '0021_auto_20210208_1831'),
    ]

    operations = [
    ]
