# Generated by Django 3.0.10 on 2021-02-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0021_auto_20210208_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='scientific_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='university.ScientificSociety', verbose_name='Scientific Societies'),
        ),
    ]
