# Generated by Django 3.0.10 on 2021-02-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0022_merge_20210208_1902'),
        ('university', '0022_merge_20210208_1905'),
    ]

    operations = [
    ]
