# Generated by Django 3.0.10 on 2021-02-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0023_auto_20210209_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='staff',
            field=models.ManyToManyField(related_name='rewards', to='university.Staff', verbose_name='Staff'),
        ),
    ]
