# Generated by Django 3.0.10 on 2021-02-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0023_merge_20210208_1906'),
        ('university', '0023_auto_20210209_1135'),
    ]

    operations = [
    ]
