# Generated by Django 3.0.10 on 2021-02-11 09:58

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0024_auto_20210210_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultytranslation',
            name='council_of_employers',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Council of employers'),
        ),
        migrations.AlterField(
            model_name='materialbasenodetranslation',
            name='local_title',
            field=models.CharField(blank=True, help_text='Additional field with local name \n    for best admin usage experience. Will be filled \n    from title field, if  field empty.', max_length=100, null=True, verbose_name='Local title'),
        ),
        migrations.AlterField(
            model_name='specialitytranslation',
            name='educational_level',
            field=models.CharField(choices=[('Junior bachelor', 'Junior bachelor'), ('Bachelor', 'Bachelor'), ('Doctor of Philosophy', 'Doctor of Philosophy'), ('Master', 'Master'), ('PHD', 'PHD')], max_length=200, null=True, verbose_name='Educational Level'),
        ),
        migrations.AlterField(
            model_name='specialitytranslation',
            name='form_of_studying',
            field=models.CharField(choices=[('Day', 'Day'), ('Extramural', 'Extramural'), ('Day, Extramural', 'Day, Extramural')], max_length=200, null=True, verbose_name='Form of studying'),
        ),
    ]
