# Generated by Django 3.0.10 on 2021-02-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0022_merge_20210208_1905'),
        ('university', '0025_auto_20210211_1158'),
    ]

    operations = [
    ]
