# Generated by Django 3.0.10 on 2021-02-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0024_merge_20210209_1209'),
        ('university', '0026_merge_20210216_0916'),
    ]

    operations = [
    ]
