# Generated by Django 3.0.10 on 2021-02-22 11:52

from django.db import migrations, models
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0026_merge_20210216_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='disciplines',
            field=models.ManyToManyField(blank=True, null=True, to='university.Discipline'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emails',
            field=multi_email_field.fields.MultiEmailField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
    ]
