# Generated by Django 3.0.10 on 2021-02-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0027_auto_20210222_1352'),
        ('university', '0027_merge_20210217_1500'),
    ]

    operations = [
    ]
