# Generated by Django 3.0.10 on 2021-02-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0028_auto_20210222_1418'),
        ('university', '0028_merge_20210222_1354'),
    ]

    operations = [
    ]
