# Generated by Django 3.0.10 on 2021-02-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0029_auto_20210223_1954'),
        ('university', '0029_merge_20210222_1422'),
    ]

    operations = [
    ]
