# Generated by Django 3.0.10 on 2021-02-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0030_merge_20210223_2026'),
        ('university', '0030_auto_20210223_2034'),
    ]

    operations = [
    ]
