# Generated by Django 3.0.10 on 2021-02-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0030_auto_20210223_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cathedras', to='university.Faculty', verbose_name='Faculty'),
        ),
    ]
