# Generated by Django 3.0.10 on 2021-02-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0031_merge_20210223_2035'),
        ('university', '0031_auto_20210228_1427'),
    ]

    operations = [
    ]
