# Generated by Django 3.0.10 on 2021-02-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0031_auto_20210228_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffcathedra',
            options={'verbose_name': 'Department staff', 'verbose_name_plural': 'Department staffs'},
        ),
        migrations.AlterModelOptions(
            name='staffcathedratranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Department staff Translation'},
        ),
        migrations.AlterField(
            model_name='scientificsociety',
            name='staff',
            field=models.ManyToManyField(to='university.StaffCathedra', verbose_name='Staff'),
        ),
    ]
