# Generated by Django 3.0.10 on 2021-02-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0032_auto_20210228_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cathedra',
            options={'verbose_name': 'Departments', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='cathedratranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Departments Translation'},
        ),
        migrations.AlterField(
            model_name='staffcathedra',
            name='cathedras',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Cathedra', verbose_name='Department'),
        ),
    ]
