# Generated by Django 3.0.10 on 2021-02-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0032_merge_20210228_1428'),
        ('university', '0032_auto_20210228_1546'),
    ]

    operations = [
    ]
