# Generated by Django 3.0.10 on 2021-02-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0033_auto_20210228_1941'),
        ('university', '0033_merge_20210228_1548'),
    ]

    operations = [
    ]
