# Generated by Django 3.0.10 on 2021-03-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0034_merge_20210228_1954'),
        ('university', '0034_auto_20210303_2220'),
    ]

    operations = [
    ]
