# Generated by Django 3.0.10 on 2021-06-08 12:17

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0035_merge_20210303_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Staff certification',
                'verbose_name_plural': 'Staff certifications',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaffScienceWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Staff science work',
                'verbose_name_plural': 'Staff science works',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='cathedratranslation',
            name='goal',
        ),
        migrations.AddField(
            model_name='staff',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='staff_science_works', to='university.StaffCertification'),
        ),
        migrations.AddField(
            model_name='staff',
            name='scienceworks',
            field=models.ManyToManyField(blank=True, related_name='staff_science_works', to='university.StaffScienceWork'),
        ),
        migrations.CreateModel(
            name='StaffScienceWorkTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('content', djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Content')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='university.StaffScienceWork')),
            ],
            options={
                'verbose_name': 'Staff science work Translation',
                'db_table': 'university_staffsciencework_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaffCertificationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('content', djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Content')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='university.StaffCertification')),
            ],
            options={
                'verbose_name': 'Staff certification Translation',
                'db_table': 'university_staffcertification_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
