# Generated by Django 3.0.10 on 2021-06-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0037_auto_20210609_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardtranslation',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='educational_level',
            field=models.IntegerField(choices=[(0, 'Junior bachelor'), (1, 'Bachelor'), (2, 'Master'), (3, 'PHD'), (4, 'Doctor of Philosophy')], null=True, verbose_name='Educational Level'),
        ),
        migrations.AlterField(
            model_name='staffcertificationtranslation',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
    ]
