# Generated by Django 3.1.5 on 2021-01-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210119_1129'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery'),
        ),
    ]
