# Generated by Django 3.0.10 on 2021-02-03 18:07

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeedtranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='papertranslation',
            name='story',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Story'),
        ),
    ]
