# Generated by Django 3.1.5 on 2021-01-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210120_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='header',
            field=models.ImageField(default='', upload_to='headers', verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='news_feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='news.newsfeed'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='story',
            field=models.TextField(max_length=1500, verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
