# Generated by Django 3.1.5 on 2021-01-19 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_paper_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
