# Generated by Django 3.1.5 on 2021-01-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210202_1507'),
        ('news', '0003_auto_20210126_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery', verbose_name='Gallery'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='news_feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='news.newsfeed', verbose_name='News Feed'),
        ),
    ]
