# Generated by Django 3.0.10 on 2021-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210215_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriestranslation',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
    ]
