# Generated by Django 3.0.10 on 2021-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_paper_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertranslation',
            name='authors',
            field=models.CharField(default='Стукан Тетяна', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
