# Generated by Django 3.0.10 on 2021-02-24 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_papertranslation_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Article date'),
        ),
        migrations.AlterField(
            model_name='papertranslation',
            name='authors',
            field=models.CharField(max_length=200, verbose_name='Authors'),
        ),
    ]
