# Generated by Django 3.0.10 on 2021-02-26 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djangocms_text_ckeditor.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210224_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='announcements', upload_to='', verbose_name='Image')),
                ('attach', models.URLField(blank=True, null=True, verbose_name='Attach')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Announcement date')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnnouncementTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.Announcement')),
            ],
            options={
                'verbose_name': 'announcement Translation',
                'db_table': 'news_announcement_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
