# Generated by Django 3.0.10 on 2021-02-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210226_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='announcementtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Announcement Translation'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paper', 'verbose_name_plural': 'Papers'},
        ),
    ]
