# Generated by Django 3.0.10 on 2021-03-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210226_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active announcement'),
        ),
    ]
