# Generated by Django 3.0.10 on 2021-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210305_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementtranslation',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
